select
    {{ dbt_utils.generate_surrogate_key(['person_id', 'year']) }}       as person_key,
    {{ dbt_utils.generate_surrogate_key(['date_day']) }}                as date_key,
    date_day,
    time_of_day,
    general_mood,
    weight,
    systolic_reading,
    diastolic_reading,
    bp_reading,
    bp_category,
    systolic_change_from_previous_day,
    diastolic_change_from_previous_day,
    if(systolic_reading < 120, 1,0) as has_met_daily_systolic_goal,
    if(diastolic_reading < 80, 1,0) as has_met_daily_diastolic_goal,
from {{ ref('int_bp_readings') }}
